NAME=RPG-Properties
BIN_LIB=RPGPROP
DBGVIEW=*SOURCE
TGTRLS=V7R3M0

#----------

all: property.rpgle
	@echo "Built all"

#----------

property.rpgle:
	system "CRTRPGMOD MODULE($(BIN_LIB)/PROPERTY) SRCSTMF('QSOURCE/property.rpgle') TEXT('$(NAME)') REPLACE(*YES) DBGVIEW($(DBGVIEW)) TGTRLS($(TGTRLS)) INCDIR('QSOURCE')"
	system "CRTSRVPGM SRVPGM($(BIN_LIB)/PROPERTY) MODULE($(BIN_LIB)/PROPERTY) EXPORT(*ALL) TEXT('$(NAME)') REPLACE(*YES) ACTGRP(PROPERTY)"
	system "DLTOBJ OBJ($(BIN_LIB)/PROPERTY) OBJTYPE(*MODULE)"
	system "CRTBNDDIR BNDDIR($(BIN_LIB)/PROPERTY) TEXT('$(NAME)')"
	system "ADDBNDDIRE BNDDIR($(BIN_LIB)/PROPERTY) OBJ(($(BIN_LIB)/PROPERTY *SRVPGM))"
	system "CRTBNDRPG PGM($(BIN_LIB)/PROPTEST) SRCSTMF('QSOURCE/proptest.rpgle') TEXT('RPG-Properties test program') REPLACE(*YES) DBGVIEW($(DBGVIEW)) TGTRLS($(TGTRLS)) INCDIR('QSOURCE')"
	
clean:
	system "CLRLIB $(BIN_LIB)"